fix: Links in POSTINSTALL should open in new tab
firebase/firebase-tools-ui pull request #741
Opened 2022-04-05 15:46 UTC by NothingEverHappens

2022-04-07 18:55 UTC, yuchenshi approved these changes

2022-04-07 18:55 UTC, yuchenshi commented on src/components/common/Callout.tsx
> +  console.log(actions);
```suggestion
```

2022-04-13 20:58 UTC, joehan requested changes

2022-04-13 20:58 UTC, joehan commented on src/components/Extensions/Details/DetailCard/Tabs/ParamList.tsx
> +            <code>firebase emulators:start</code>
This should be `firebase ext:configure ${instanceid} --local`

2022-04-18 18:57 UTC, merged